name             'cens-base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cens-base'
long_description 'Installs/Configures cens-base'
version          '0.1.0'
